---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: cluster_name
---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: cluster_name
  labels:
    name: cluster_name
    cloud: auto-detect
    vendor: auto-detect
    cluster.open-cluster-management.io/clusterset: gitops-clusters
spec:
  hubAcceptsClient: true
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: auto-import-secret
  namespace: cluster_name
stringData:
  autoImportRetry: "2"
  token: cluster_token 
  server: https://server_url:6443
type: Opaque
---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: cluster_name
  namespace: cluster_name
spec:
  clusterName: cluster_name
  clusterNamespace: cluster_name
  clusterLabels:
    name: cluster_name
    cloud: auto-detect
    vendor: auto-detect
    cluster.open-cluster-management.io/clusterset: gitops-clusters
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
