---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: namespace-policy-placement
  namespace: default
spec:
  clusterConditions: []
  clusterSelector:
    matchExpressions:
      - key: vendor
        operator: In
        values:
          - OpenShift
